### ISSUE TITLE
It doesn't desapear

### ISSUE THREAD

**Issue by JovenOculto** [lucahammer/tweetXer#11]
The blue banner/thing is stuck forever, I uninstall the browser and re install it (opera GX) and its still there. It's extremely annoying.

**Comment by 0DeltaWaves** [comment]
Having the same problem. Clicking "remove tweetxer" makes the banner disappear but it returns once you reload or load a new page. Tampermonkey shows no scripts installed. This is a major problem due to the script causing any twitter url to redirect to my profile
