### ISSUE TITLE
Error message when I tried to paste the script into the console

### ISSUE THREAD

**Issue by Kaetrin** [lucahammer/tweetXer#16]
Hi, I was following along with the YouTube instructions and opened the console on Firefox via F12 on Windows. I went to the console tab and tried to copy the script but received the following error message and the script would not copy.
Loading failed for the <script> with source “https://abs.twimg.com/responsive-web/client-web/vendor.42364e5a.js”. [home:333:401](https://twitter.com/home)
TypeError: a.default.detectStore(...) is undefined
[h1-check.js:1:1301](moz-extension://51a7da85-0671-4d40-bc93-784648a848c0/h1-check.js)
Content-Security-Policy: The page’s settings blocked the loading of a resource (object-src) at data:i because it violates the following directive: “object-src 'none'”
(Please let me know if you need anything else but I think that's the entire error message.)
My Twitter account is currently private - I'm not sure if that matters or if the problem is more local? Can you advise please? 

Thank you in advance!

**Comment by lucahammer** [comment]
The error messages are unrelated to the script.

You need to type "allow pasting" or "allow paste" first. Then you can paste the code. Please re-open if it didn't work.

**Comment by Kaetrin** [comment]
thank you!

**Comment by Kaetrin** [comment]
Okay, I tried that and I was able to paste the code into the console but the error message did not pop up to select tweet header.js
I got this error message Loading failed for the <script> with source “https://abs.twimg.com/responsive-web/client-web/vendor.dcc978ca.js”.
When I tried again, I got a syntax error.

I'm so bad at this :(

**Comment by Kaetrin** [comment]
I "think" I worked it out. Thank you.
