### ISSUE TITLE
Not deleting tweets, possibly outdated CSS selector 

### ISSUE THREAD

**Issue by gambolputty** [lucahammer/tweetXer#19]
These lines don't work in my case:

https://github.com/lucahammer/tweetXer/blob/f96948f862b3774e090676b5401a06245d9487d8/tweetXer.js#L424-L428

Resulting in the following console statements, after selecting the tweet-header.js file:

![image](https://github.com/user-attachments/assets/a5a26ad4-375c-46dc-a1a1-96e5b39ff099)

No tweets are deleted in Chrome and Firefox. The selector `[data-testid="TopNavBar"]"` is not matching any elements.

When I replace the line that determines the tweet count with a number, it does work and all my tweets get deleted.

![image](https://github.com/user-attachments/assets/d4ca57ac-b10a-4858-a1d7-458970ac8f81)

**Comment by satmandu** [comment]
I'm also seeing the same `document.querySelector('[data-testid="DashButton_ProfileIcon_Link"]').click()`error.

I see the number of tweets to be deleted after I upload the json file, and then I get a progress bar, but nothing else happens.

I edited the TweetsXer.TweetCount lines as above to the number of tweets I have, but nothing changed.

**Comment by satmandu** [comment]
```
Error in parsing value for ‘object-fit’.  Declaration dropped. [satmandu:1:1](https://x.com/satmandu#)
Error in parsing value for ‘object-fit’.  Declaration dropped. 3 [satmandu:1:1](https://x.com/satmandu#)
File contains Tweets.[ TweetXer.user.js:96:29](moz-extension://7dae391f-81d9-4d2a-98e9-530e93fc5221/%20TweetXer.user.js#1)
Skipping oldest 93303 Tweets[ TweetXer.user.js:127:29](moz-extension://7dae391f-81d9-4d2a-98e9-530e93fc5221/%20TweetXer.user.js#1)
```

**Comment by satmandu** [comment]
Curiously enough, editing the `TweetXer.Tweetcount` as above did allow me to progress through and delete all of my follows, which I reported in https://github.com/lucahammer/tweetXer/issues/23
