### ISSUE TITLE
BUG or FEATURES?

### ISSUE THREAD

**Issue by everythingability** [lucahammer/tweetXer#21]
Firstly, thank you for doing this. Wonderful work - but I had a few issues....

I normally use Chrome (latest) Mac Sonoma M2  so I used a "fresh" Firefox instal, so maybe found some quicks you'd missed ages ago,l and firstly.

When pasting in the script the first weird issue I faced was having to type "allow pasting" or something. I had to mess about to even get this to work, for example, you can't paste in "allow pasting" it seems. Dur! :-) Maybe add that to the tutorial bit?

I used my tweet-headers.js file and it said this...

<img width="920" alt="______everythingabili____X_and_Downloads" src="https://github.com/user-attachments/assets/aa863e55-35d5-4194-802d-8ace2325dafa">

... which displays as NaN in the UI as well. And it seems to enter a loop and not much gets reported to screen, but I think it may have actually worked... I tried it a few times and I got the progress bar when entering **10** into the **Enter how many Tweets to skip field**. I also got the progress bar... and a message telling me 724 tweets deleted... (I used to have a Python script to do this once a month for me after Elon joined but, well, exactly). My script I think also fails to delete really old tweets, too... I reckon I have a few danglers lurking in there, cos they never show up anywhere... 

Because the progress bar has no background, I can't tell IF the script has finished. There's no "Done" message in the console... is it hanging ? Hard to tell. Oh hang on, I'm running it again, and there IS a background, and for me, I think it gets to the end and then doesn't end the loop.... sorta hangs. I'm running the script over a few times and it seems to find new ones to delete, though my profile is already showing itself empty again ( what a feat this script is! Thank you).

So, it seems to have done the job but a few re-runs were required, and I think I have too many likes to bother deleting them (33,000 -ish). ... and I hit the rate limit.

I hope this helps... 

Tom

**Comment by lucahammer** [comment]
By default the script is not aware of already removed Tweets, so it will try to remove the same ones over and over again if run again. There is a mechanism where it tries to calculate the difference between posts on the profile and in the file but it's buggy.

I added some more messages, that should make it easier to use.

**Comment by everythingability** [comment]
Hi ...

It still does the NaN thing UNLESS I put a number like 2 or 10 in the text entry.

It tried the slow delete option and there are still 78 tweets lurking. I reckon they were maybe made before Elon 4Chan'd twitter or summat.

I reckon that's as good as it can get.

It deleted my last/first/only tweet linking to your script :-) Do'h! Ah well...

Thanks again, great work

Tom

**Comment by everythingability** [comment]
Oh this happened... at the end of the script.... just in case it's handy.

VM638:445 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'scrollIntoView')
    at HTMLInputElement.slowDelete (<anonymous>:445:45)
slowDelete @ VM638:445Understand this errorAI
main.4e2bed9a.js:1 
        
        
       POST https://x.com/i/api/1.1/jot/error_log.json net::ERR_BLOCKED_BY_CLIENT
