### ISSUE TITLE
Running the script doesn't delete the tweets - Error 422

### ISSUE THREAD

**Issue by CelianGdfrd** [lucahammer/tweetXer#26]
![image](https://github.com/user-attachments/assets/49c93701-e4c9-494f-87b1-ea5179f5495c)

Hi, I believe I didn't make any mistake while running the script, but the tweets don't delete, and my console is filled with error messages.

Is there something wrong please ?

**Comment by lucahammer** [comment]
Hi, you need to run the script while you are on x.com, not on GitHub.

**Comment by CelianGdfrd** [comment]
I'm so sorry. It works correctly now. Thank you so much.
