### ISSUE TITLE
Some tweets remaining

### ISSUE THREAD

**Issue by andatalily** [lucahammer/tweetXer#8]
Thank you so much! It worked for most of my tweets but I have some 1.5k tweets that don't appear on my profile and weren't included in the amount of tweets to be deleted in the blue bar. Is there anything I can do to fix this?

**Comment by apolostudio** [comment]
yep same here, i think it may be replies to posts that have already been deleted. I've seen multiple examples

**Comment by helioloureiro** [comment]
My replies remained.  Is there a way to delete them as well?

**Comment by lucahammer** [comment]
Can you check if the ID of the Tweets that remained are in the tweet-headers.js?

If you look at the post, the number part of the URL.
Example: https://x.com/luca/status/1708542965877002479 has the ID 1708542965877002479

**Comment by Manuel5cc** [comment]
Some tweets might still appear due to cache. If they were present in the files they should be deleted. If not, a rerun could fix it.

**Comment by allenea** [comment]
I also had about 1.5K tweets under "replies". I've manually deleted what I could. There are still "Repost" things that don't show RT/Un-RT, but are still on the profile. Overall, this works really well.

**Comment by lucahammer** [comment]
Since version 0.6.5 TweetXer slow delete removes replies as well. It's under "Advanced options" and can be used to clean remaining Tweets from the profile.

This does not fix the ghost Tweets, where the count on the profile says there are still Tweets, but they don't show up on the profile.
